# Generated by Django 5.2.11 on 2026-03-13 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('exa_cod', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('exa_nom', models.CharField(max_length=100)),
                ('exa_des', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPregunta',
            fields=[
                ('tip_pre_cod', models.IntegerField(primary_key=True, serialize=False)),
                ('tip_pre_nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('int_cod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('exa_num_int', models.IntegerField(default=1)),
                ('exa_fec_ini', models.DateTimeField(auto_now_add=True)),
                ('exa_fec_fin', models.DateTimeField(blank=True, null=True)),
                ('exa_pun_tot', models.IntegerField(default=0)),
                ('exa_cod', models.ForeignKey(db_column='exa_cod', on_delete=django.db.models.deletion.CASCADE, to='exams.examen')),
                ('usu_cod', models.ForeignKey(db_column='usu_cod', on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('pre_cod', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('pre_tex', models.CharField(max_length=200)),
                ('pre_fot', models.CharField(blank=True, max_length=200, null=True)),
                ('pre_pun', models.IntegerField(default=0)),
                ('pre_tie', models.IntegerField(default=0)),
                ('exa_cod', models.ForeignKey(db_column='exa_cod', on_delete=django.db.models.deletion.CASCADE, to='exams.examen')),
                ('tip_pre_cod', models.ForeignKey(blank=True, db_column='tip_pre_cod', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.tipopregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('opc_cod', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('opc_tex', models.CharField(max_length=100)),
                ('opc_cor', models.BooleanField(default=False)),
                ('pre_cod', models.ForeignKey(db_column='pre_cod', on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='exams.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('res_cod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('res_tex', models.CharField(blank=True, max_length=200, null=True)),
                ('res_pun', models.IntegerField(default=0)),
                ('res_cor', models.BooleanField(default=False)),
                ('int_cod', models.ForeignKey(db_column='int_cod', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='exams.intento')),
                ('opc_cod', models.ForeignKey(blank=True, db_column='opc_cod', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.opcion')),
                ('pre_cod', models.ForeignKey(db_column='pre_cod', on_delete=django.db.models.deletion.CASCADE, to='exams.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_cod', models.ForeignKey(db_column='cat_cod', on_delete=django.db.models.deletion.CASCADE, to='users.categoria')),
                ('exa_cod', models.ForeignKey(db_column='exa_cod', on_delete=django.db.models.deletion.CASCADE, to='exams.examen')),
            ],
            options={
                'unique_together': {('cat_cod', 'exa_cod')},
            },
        ),
        migrations.CreateModel(
            name='ExamenCategoriaCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_preguntas', models.IntegerField(default=0)),
                ('cat_cod', models.ForeignKey(db_column='cat_cod', on_delete=django.db.models.deletion.CASCADE, to='users.categoria')),
                ('com_cod', models.ForeignKey(db_column='com_cod', on_delete=django.db.models.deletion.CASCADE, to='users.competencia')),
                ('exa_cod', models.ForeignKey(db_column='exa_cod', on_delete=django.db.models.deletion.CASCADE, to='exams.examen')),
            ],
            options={
                'unique_together': {('exa_cod', 'cat_cod', 'com_cod')},
            },
        ),
        migrations.CreateModel(
            name='PreguntaCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_cod', models.ForeignKey(db_column='com_cod', on_delete=django.db.models.deletion.CASCADE, to='users.competencia')),
                ('pre_cod', models.ForeignKey(db_column='pre_cod', on_delete=django.db.models.deletion.CASCADE, to='exams.pregunta')),
            ],
            options={
                'unique_together': {('pre_cod', 'com_cod')},
            },
        ),
    ]
