# Generated by Django 5.2.11 on 2026-03-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='pre_fot',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
    ]
