# Generated by Django 5.2.11 on 2026-03-18 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cat_cod', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cat_nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('com_cod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('com_nom', models.CharField(max_length=150)),
                ('com_des', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('ran_sig', models.IntegerField(primary_key=True, serialize=False)),
                ('ran_nom', models.CharField(max_length=50)),
                ('ran_pun_min', models.IntegerField(default=0)),
                ('ran_pun_max', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usu_cod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('usu_dni', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('usu_nom', models.CharField(max_length=100)),
                ('usu_sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('usu_edad', models.IntegerField(default=0)),
                ('usu_fec_ult', models.DateField(blank=True, null=True)),
                ('usu_reg', models.DateField(auto_now_add=True)),
                ('usu_zon', models.CharField(blank=True, max_length=50, null=True)),
                ('usu_age', models.IntegerField(default=0)),
                ('usu_pun_tot', models.IntegerField(default=0)),
                ('is_staff', models.BooleanField(default=False)),
                ('cat_cod', models.ForeignKey(blank=True, db_column='cat_cod', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.categoria')),
                ('ran_sig', models.ForeignKey(blank=True, db_column='ran_sig', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rango')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
