# Generated by Django 5.2.11 on 2026-03-13 18:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cat_cod', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cat_nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('com_cod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('com_nom', models.CharField(max_length=50)),
                ('com_des', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('ran_sig', models.IntegerField(primary_key=True, serialize=False)),
                ('ran_nom', models.CharField(max_length=50)),
                ('ran_pun_min', models.IntegerField(default=0)),
                ('ran_pun_max', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('usu_cod', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('usu_dni', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('usu_nom', models.CharField(max_length=100)),
                ('usu_sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('usu_edad', models.IntegerField(default=0)),
                ('usu_fec_ult', models.DateField(blank=True, null=True)),
                ('usu_reg', models.DateField(auto_now_add=True)),
                ('usu_zon', models.CharField(blank=True, max_length=50, null=True)),
                ('usu_age', models.IntegerField(default=0)),
                ('usu_pun_tot', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('cat_cod', models.ForeignKey(blank=True, db_column='cat_cod', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.categoria')),
                ('ran_sig', models.ForeignKey(blank=True, db_column='ran_sig', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rango')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
