# Generated by Django 5.2.11 on 2026-03-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='com_nom',
            field=models.CharField(max_length=150),
        ),
    ]
